import { createMeetings } from './meeting-ui.js?v=ieum5';
import { createFeatures } from './feature-ui.js?v=ieum5';
import { CITIES, TIMES, INTERESTS, QUESTIONS, SAMPLE_USER, PEOPLE, NAV } from './data.js?v=ieum5';
import { match, recommend, reasons, profileSummary, draftOpener, normalizeProfile, readState, saveState, escapeHTML as esc } from './core.js?v=ieum5';
import { icon } from './icons.js?v=ieum5';
import { generate, cancelAI } from './ai.js?v=ieum5';

const openerDrafts=new Map();
const storage={getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)};
let state=readState(storage);
let view=NAV.some(n=>n.id===location.hash.slice(1))?location.hash.slice(1):'discover';
let filters={city:'전체',gender:'all',minAge:19,maxAge:39,sameTime:false,sameArea:false};
let draft=null, surveyStep=0, aiContext=null, aiBusy=false, toastTimer, lastFocus;
const page=document.getElementById('content'),modal=document.getElementById('modal'),modalContent=document.getElementById('modal-content');
const user=()=>({...state.profile||SAMPLE_USER,mbti:features.extra.mbti});
const personById=id=>PEOPLE.find(p=>p.id===id);
const btn=(label,action,extra='',style='primary')=>`<button class="btn ${style}" data-action="${action}" ${extra}>${label}</button>`;
const options=(items,selected)=>items.map(item=>`<option value="${esc(item)}" ${item===selected?'selected':''}>${esc(item)}</option>`).join('');
const tags=(items,common=[])=>`<div class="tags">${items.map(t=>`<span class="tag ${common.includes(t)?'shared':''}">${esc(t)}</span>`).join('')}</div>`;
function persist(){if(!saveState(storage,state))toast('이 브라우저에서는 저장이 어려워요. 현재 화면에서는 계속 이용할 수 있어요.');}
function toast(message){clearTimeout(toastTimer);const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
function renderNav(){for(const id of ['desktop-nav','mobile-nav'])document.getElementById(id).innerHTML=NAV.map(n=>`<a class="nav-item ${view===n.id?'active':''}" href="#${n.id}" ${view===n.id?'aria-current="page"':''}>${icon(n.icon)}<span>${n.label}</span></a>`).join('');}
function navigate(next){closeModal();if(location.hash===`#${next}`){view=next;render();}else location.hash=next;}
function intro(eyebrow,title,subtitle,action=''){return `<div class="page-intro"><div><div class="eyebrow">${icon('pin')}${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;}
function card(m){const p=m.person,liked=state.likes.includes(p.id);return `<article class="person-card"><div class="portrait"><div class="portrait-bg p${p.photo}" role="img" aria-label="가상의 ${esc(p.name)} 프로필 사진"></div><span class="photo-tag">${icon(m.traits.length>=3?'heart':'pin')}${m.traits.length>=3?'취향이 닮았어요':m.areas.length?'생활권이 가까워요':'새로운 인연'}</span><div class="portrait-info"><h3>${esc(p.name)}<span>${p.age}</span></h3><p>${esc(p.city)} · ${esc(p.job)}</p></div><button class="profile-open" aria-label="${esc(p.name)} 프로필 보기" data-action="detail" data-id="${p.id}"></button></div><div class="person-body"><p class="person-quote">${esc(p.quote)}</p><div class="profile-traits"><span class="mbti-tag">${esc(p.mbti)}</span>${tags(p.interests.slice(0,3),m.interests)}</div><div class="compatibility"><span>${icon('pin')}${m.areas.length?`${esc(m.areas.join(' · '))} 생활권이 겹쳐요`:'만남 지역을 함께 정해보세요'}</span><span>${icon('clock')}${m.times.length?`${esc(m.times[0])}에 시간이 맞아요`:'편한 시간을 먼저 맞춰보세요'}</span></div><div class="card-actions"><button class="text-button" data-action="detail" data-id="${p.id}">우리의 공통점 ${icon('chevron')}</button><button class="heart-button ${liked?'selected':''}" data-action="like" data-id="${p.id}" aria-label="${esc(p.name)} ${liked?'관심 취소':'관심에 저장'}" aria-pressed="${liked}">${icon('heart')}</button></div></div></article>`;}
function empty(title,body,button,which='heart'){return `<div class="empty-state"><div class="empty-icon">${icon(which)}</div><h2>${title}</h2><p>${body}</p>${button||''}</div>`;}
function sidebar(){const u=user();return `<aside class="sidebar"><section class="side-panel"><div class="side-heading"><h2>내 만남의 기준</h2><button class="text-button" data-action="survey">설정</button></div><div class="my-summary">${features.avatar()}<div><b>${state.profile?esc(u.name)+' 님':'아직 알아가는 중'}</b><p>${state.profile?`${esc(u.city)} · ${u.age}세`:'내 취향을 알려주세요'}</p></div></div><div class="criteria"><div class="criteria-row">${icon('pin')}<div><label>자주 오가는 곳</label><p>${state.profile?esc(u.areas.join(' · ')):'전주 · 완주 (예시)'}</p></div></div><div class="criteria-row">${icon('clock')}<div><label>만나기 좋은 시간</label><p>${state.profile?esc(u.times.join(' · ')):'평일 저녁 · 토요일 오후 (예시)'}</p></div></div><div class="criteria-row">${icon('heart')}<div><label>함께 나누고 싶은 취향</label>${tags(state.profile?u.interests:['카페','산책','독서'])}</div></div></div></section>${features.compactPremium()}${features.compactFestival()}<p class="smallprint">추천 프로필은 체험용 가상 인물입니다.<br>관심·설문은 이 기기에만 저장됩니다.<br><button data-action="about">서비스와 추천 방식 안내</button></p></aside>`;}
function discover(){const matches=recommend(user(),{...filters,hidden:state.hidden});return `${intro('전북에서 만나요','일상이 닮은 사람, 가까운 곳에서.','멀리 찾지 않아도, 잘 맞는 사람은 있으니까.',`<button class="region-button" data-action="filters">${icon('pin')}${filters.city==='전체'?'전북 전체':esc(filters.city)}${icon('down')}</button>`)}<div class="layout"><div class="discovery-main"><div class="survey-strip"><div class="strip-icon">${icon('note')}</div><div class="strip-copy"><strong>${state.profile?`${esc(user().name)} 님의 일상에 맞춰 소개할게요`:'끌리는 사람보다, 잘 맞는 사람을 찾으려면'}</strong><p>${state.profile?'내 성향과 생활권을 반영한 추천이에요.':'내 취향과 연애 스타일을 먼저 알려주세요.'}</p></div>${btn(state.profile?'성향 수정':'2분 성향 찾기','survey','','small primary')}</div><div class="filter-row" aria-label="추천 필터"><button class="filter-chip ${filters.gender==='all'?'active':''}" data-action="filter-gender" data-value="all" aria-pressed="${filters.gender==='all'}">전체</button><button class="filter-chip ${filters.gender==='woman'?'active':''}" data-action="filter-gender" data-value="woman" aria-pressed="${filters.gender==='woman'}">여성</button><button class="filter-chip ${filters.gender==='man'?'active':''}" data-action="filter-gender" data-value="man" aria-pressed="${filters.gender==='man'}">남성</button><button class="filter-chip ${filters.sameTime?'active':''}" data-action="filter-time" aria-pressed="${filters.sameTime}">${icon('clock')}같은 시간대</button><button class="filter-chip more" data-action="filters">${icon('sliders')}조건 설정</button></div><div class="results-heading"><h2>오늘의 잇음<span class="count">${matches.length}</span></h2><span class="meta">${state.profile?'성향 · 생활권 · 시간 기준':'가상 프로필로 둘러보기'}</span></div>${matches.length?`<div class="profile-grid">${matches.map(card).join('')}</div>`:empty('아직 조건에 맞는 사람이 없어요','지역이나 시간 조건을 조금 넓혀보세요.',btn('추천 조건 초기화','reset-filters'),'compass')}<p class="endnote">${state.profile?'지금 보이는 사람은 모두 가상 프로필이에요.':'전주 생활권의 예시 취향을 기준으로 소개하고 있어요.'}<br>마음이 가는 사람이 있다면 관심에 저장해 보세요.</p></div>${sidebar()}</div>`;}
function likes(){const list=state.likes.filter(id=>!state.hidden.includes(id)).map(personById).filter(Boolean).map(p=>match(user(),p));return `${intro('마음이 머문 곳','한 번 더 보고 싶은 사람','관심 목록은 나만 볼 수 있어요. 상대에게 알림이 가지 않아요.')}<div class="layout"><div>${meetings.panel(true)}${list.length?`<div class="results-heading"><h2>저장한 프로필<span class="count">${list.length}</span></h2></div><div class="profile-grid">${list.map(card).join('')}</div>`:empty('마음이 가는 사람을 담아보세요','프로필의 하트를 누르면 이곳에서 다시 볼 수 있어요.',btn('오늘의 잇음 보기','navigate','data-view="discover"'))}</div>${sidebar()}</div>`;}
function profile(){const u=state.profile;if(!u)return `${intro('내 프로필','좋은 만남은, 나를 아는 것부터.','짧은 질문으로 나의 관계 취향을 알아보세요.')}<div class="wide-panel">${features.profileCard()}${empty('어떤 일상을 함께하고 싶나요?','생활권, 시간, 취향과 다섯 가지 질문으로 나를 위한 추천을 만들어요.',btn('내 성향 찾기','survey'),'note')}<p class="endnote">이름 대신 닉네임을 사용할 수 있어요.<br>입력한 정보는 이 기기에만 저장돼요.</p>${features.membership()}</div>`;
  const summary=profileSummary(u);return `${intro('내 프로필',`${esc(u.name)} 님의 만남 취향`,'원하는 관계도, 일상의 속도도 언제든 바뀔 수 있어요.')}<div class="wide-panel">${features.profileCard()}<section class="content-panel"><div class="section-header"><div><span class="source-tag">설문 응답 요약</span><h2>${esc(u.name)} · ${u.age}</h2></div>${btn('프로필 수정','survey','','secondary small')}</div><h3 class="profile-summary-title">${summary.title}</h3><p class="body-copy">${esc(summary.body)}</p>${tags(summary.tags)}<dl class="info-grid"><div><dt>나의 생활권</dt><dd>${esc(u.areas.join(' · '))}</dd></div><div><dt>만나기 좋은 시간</dt><dd>${esc(u.times.join(' · '))}</dd></div><div><dt>좋아하는 것</dt><dd>${esc(u.interests.join(' · '))}</dd></div><div><dt>소개받고 싶은 사람</dt><dd>${{all:'성별 무관',woman:'여성',man:'남성'}[u.seeking]}</dd></div></dl>${u.note?`<div class="note-box"><strong>내가 더 들려준 이야기</strong><br>${esc(u.note)}</div>`:''}</section>${features.membership()}<section class="content-panel"><div class="section-header"><h2>이 기기의 정보</h2></div><p class="helper">설문, 관심 목록, 만남 요청과 약속 초안은 이 브라우저에 저장돼요. 회원 가입이나 실제 상대와의 연결은 제공하지 않는 체험 버전이에요.</p><div class="action-group"><button class="text-button" data-action="restore-hidden">숨긴 프로필 다시 보기 (${state.hidden.length})</button><button class="danger-button" data-action="reset-confirm">체험 정보 초기화</button></div></section></div>`;}
function dates(){return features.dates();}
function render(){renderNav();features.header();page.innerHTML=({discover,likes,dates,profile}[view]||discover)();document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
function showModal(html){if(!modal.open)lastFocus=document.activeElement;modalContent.innerHTML=html;if(!modal.open)modal.showModal();document.body.style.overflow='hidden';modal.scrollTop=0;requestAnimationFrame(()=>modal.querySelector('h2')?.focus());}
function closeModal(){if(modal.open)modal.close();}
modal.addEventListener('close',()=>{document.body.style.overflow='';if(aiBusy){cancelAI();aiBusy=false;}lastFocus?.isConnected&&lastFocus.focus();});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
const closeButton=()=>`<button class="icon-button close-button" data-action="close" aria-label="닫기">${icon('close')}</button>`;
const modalHead=(title,sub='')=>`<div class="modal-head"><div><h2 id="modal-title" tabindex="-1">${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${closeButton()}</div>`;
const features=createFeatures({storage,state:()=>state,user,render,navigate,showModal,modalHead,btn,toast,showAI,copy,intro,meetingPanel:()=>meetings.panel()});
const meetings=createMeetings({storage,user,render,showModal,modalHead,btn,toast,planMeeting:request=>features.planMeeting(request)});
function showDetail(id){const p=personById(id);if(!p)return;const m=match(user(),p);showModal(`<div class="modal-inner"><div class="detail-portrait"><div class="portrait-bg p${p.photo}" role="img" aria-label="가상의 ${esc(p.name)} 프로필 사진"></div>${closeButton()}</div><div class="detail-title"><div><h2 id="modal-title" tabindex="-1">${esc(p.name)} · ${p.age}</h2><p>${esc(p.city)} · ${esc(p.job)} · 가상 프로필</p></div><button class="heart-button ${state.likes.includes(id)?'selected':''}" data-action="like" data-id="${id}" aria-label="${esc(p.name)} ${state.likes.includes(id)?'관심 취소':'관심에 저장'}" aria-pressed="${state.likes.includes(id)}">${icon('heart')}</button></div><p class="detail-about">${esc(p.about)}</p><div class="profile-traits"><span class="mbti-tag">${esc(p.mbti)}</span>${tags(p.interests,m.interests)}</div><section class="detail-section"><h3>우리가 함께 나눌 수 있는 것</h3><p class="helper">${state.profile?'내 설문과 비교한 공통점이에요.':'예시 취향과 비교했어요. 내 성향을 입력하면 달라져요.'}</p>${reasons(m).map(r=>`<div class="reason-item">${icon('check')}<span>${esc(r)}</span></div>`).join('')}<div class="match-explanation"><div><b>${m.traits.length}<span> / 5</span></b><span>같은 성향 응답</span></div><div><b>${m.interests.length}</b><span>공통 관심사</span></div><div><b>${m.times.length}</b><span>겹치는 시간대</span></div></div><button class="text-button accent" data-action="ai-reason" data-id="${id}">AI로 공통점 더 읽어보기 ${icon('arrow')}</button></section><div class="action-group">${btn(`${icon('chat')}첫 대화 준비`,'opener',`data-id="${id}"`)}${btn(`${icon('calendar')}데이트 코스`,'date-for',`data-id="${id}"`,'secondary')}</div><div class="detail-section"><button class="text-button" data-action="hide" data-id="${id}">이 프로필 그만 보기</button></div></div>`);}
function toggleLike(id){if(!personById(id))return;const was=state.likes.includes(id);state.likes=was?state.likes.filter(x=>x!==id):[...state.likes,id];persist();render();modal.querySelectorAll(`[data-action="like"][data-id="${id}"]`).forEach(b=>{b.classList.toggle('selected',!was);b.setAttribute('aria-pressed',String(!was));b.setAttribute('aria-label',`${personById(id).name} ${was?'관심에 저장':'관심 취소'}`);});toast(was?'관심 목록에서 지웠어요':'관심 목록에 저장했어요. 나만 볼 수 있어요.');}
function showFilters(){showModal(`<div class="modal-inner">${modalHead('어떤 만남을 찾고 있나요?','조건은 언제든 가볍게 바꿀 수 있어요.')}<div class="field"><label for="filter-city">만나기 편한 생활권</label><select id="filter-city">${options(['전체',...CITIES],filters.city)}</select></div><div class="form-grid"><div class="field"><label for="min-age">최소 나이</label><input id="min-age" type="number" min="19" max="99" value="${filters.minAge}"></div><div class="field"><label for="max-age">최대 나이</label><input id="max-age" type="number" min="19" max="99" value="${filters.maxAge}"></div></div><label class="check-row"><input id="same-time" type="checkbox" ${filters.sameTime?'checked':''}>만날 수 있는 시간이 겹치는 사람만</label><label class="check-row"><input id="same-area" type="checkbox" ${filters.sameArea?'checked':''}>내 생활권과 겹치는 사람만</label>${!state.profile?'<div class="note-box">내 성향을 입력하기 전에는 전주·완주, 평일 저녁·토요일 오후를 예시 기준으로 사용해요.</div>':''}<p id="filter-error" class="error-message" role="alert"></p><div class="modal-footer">${btn('초기화','reset-filters','','secondary')}${btn('조건 적용','apply-filters')}</div></div>`);}
function startSurvey(){draft=state.profile?structuredClone(state.profile):{name:'',age:'',city:'전주',areas:['전주'],seeking:'all',times:[],interests:[],answers:{},note:''};surveyStep=0;showSurvey();}
function choiceList(items,key,max){return `<div class="choice-grid">${items.map(v=>`<button class="choice-button ${draft[key].includes(v)?'selected':''}" data-action="survey-choice" data-key="${key}" data-value="${esc(v)}" data-max="${max}" aria-pressed="${draft[key].includes(v)}">${esc(v)}</button>`).join('')}</div>`;}
function showSurvey(){let body='';const titles=['우리, 일상부터 알아봐요','연애에도 나만의 속도가 있죠','마지막으로, 내 이야기를 더해요'];
  if(surveyStep===0)body=`<div class="form-grid"><div class="field"><label for="nickname">닉네임</label><input id="nickname" placeholder="어떻게 불러드릴까요?" maxlength="16" value="${esc(draft.name)}" autocomplete="off"></div><div class="field"><label for="age">나이</label><input id="age" type="number" min="19" max="99" placeholder="만 19세 이상" value="${esc(draft.age)}"></div><div class="field"><label for="my-city">주로 생활하는 곳</label><select id="my-city">${options(CITIES,draft.city)}</select></div><div class="field"><label for="seeking">소개받고 싶은 사람</label><select id="seeking"><option value="all" ${draft.seeking==='all'?'selected':''}>성별 무관</option><option value="woman" ${draft.seeking==='woman'?'selected':''}>여성</option><option value="man" ${draft.seeking==='man'?'selected':''}>남성</option></select></div></div><div class="form-section"><label>자주 오가는 생활권 <span class="helper">최대 3곳</span></label>${choiceList(CITIES,'areas',3)}</div><div class="form-section"><label>만나기 편한 시간 <span class="helper">여러 개 선택 가능</span></label>${choiceList(TIMES,'times',5)}</div><div class="form-section"><label>좋아하는 것 <span class="helper">최대 5개</span></label>${choiceList(INTERESTS,'interests',5)}</div><p class="helper" style="margin-top:20px">모든 정보는 이 기기에만 저장돼요. 실명이나 연락처는 필요하지 않아요.</p>`;
  if(surveyStep===1)body=`<p class="helper">정답은 없어요. 지금의 나와 가까운 답을 골라주세요.</p>${QUESTIONS.map((q,i)=>`<section class="question"><h3>${i+1}. ${q.title}</h3><div class="answer-list" role="group" aria-label="${q.title}">${q.options.map((o,n)=>`<button class="answer-option ${draft.answers[q.id]===n?'selected':''}" data-action="answer" data-key="${q.id}" data-value="${n}" aria-pressed="${draft.answers[q.id]===n}">${o}</button>`).join('')}</div></section>`).join('')}`;
  if(surveyStep===2)body=`<div class="ai-state"><span class="source-tag">지금 선택한 응답을 정리했어요</span><h3>${profileSummary(draft).title}</h3><p>${esc(profileSummary(draft).body)}</p>${tags(profileSummary(draft).tags.slice(0,3))}</div><div class="field" style="margin-top:24px"><label for="my-note">선택지에 없는 내 이야기 <span class="helper">선택</span></label><textarea id="my-note" maxlength="300" placeholder="예: 교대근무를 해서 답장이 늦을 때가 있어요. 쉬는 날에는 같이 산책하고 싶어요.">${esc(draft.note)}</textarea><span class="helper">AI 성향 노트를 만들 때 함께 읽어요. 연락처 등 민감한 정보는 적지 않아도 돼요.</span></div>`;
  showModal(`<div class="modal-inner"><div class="step-label">${surveyStep+1} / 3 · 내 만남 취향</div>${modalHead(titles[surveyStep])}<div class="progress-dots">${[0,1,2].map(n=>`<span class="${n<=surveyStep?'active':''}"></span>`).join('')}</div>${body}<p id="survey-error" class="error-message" role="alert"></p><div class="modal-footer">${surveyStep?btn('이전','survey-back','','secondary'):''}${btn(surveyStep===2?'오늘의 잇음 보기':'다음','survey-next')}</div></div>`);
}
function collectSurvey(){if(surveyStep===0){draft.name=document.getElementById('nickname').value.trim();draft.age=Number(document.getElementById('age').value);draft.city=document.getElementById('my-city').value;draft.seeking=document.getElementById('seeking').value;}if(surveyStep===2)draft.note=document.getElementById('my-note').value.trim();}
function nextSurvey(){collectSurvey();let error='';if(surveyStep===0){if(!draft.name)error='닉네임을 입력해 주세요.';else if(!Number.isInteger(draft.age)||draft.age<19||draft.age>99)error='만 19세부터 99세까지의 나이를 입력해 주세요.';else if(!draft.areas.includes(draft.city))error='주로 생활하는 곳을 생활권에도 포함해 주세요.';else if(!draft.times.length)error='만나기 편한 시간을 하나 이상 골라주세요.';else if(!draft.interests.length)error='좋아하는 것을 하나 이상 골라주세요.';}if(surveyStep===1&&QUESTIONS.some(q=>draft.answers[q.id]===undefined))error='다섯 질문에 모두 답해 주세요.';if(error){document.getElementById('survey-error').textContent=error;return;}if(surveyStep<2){surveyStep++;showSurvey();return;}const p=normalizeProfile(draft);if(!p){document.getElementById('survey-error').textContent='입력한 정보를 다시 확인해 주세요.';return;}state.profile=p;persist();filters={...filters,gender:'all'};closeModal();navigate('discover');toast('내 취향을 반영해 추천을 새로 준비했어요.');}
function showOpener(id){const p=personById(id);if(!p)return;showModal(`<div class="modal-inner">${modalHead(`${esc(p.name)} 님에게, 첫 인사`,'공통 취향에서 시작하면 조금 더 편해져요.')}<span class="source-tag">공통 관심사로 만든 기본 문구</span><textarea id="opener-text" class="draft-text" maxlength="1800" aria-label="첫 대화 문구">${esc(openerDrafts.get(id)??draftOpener(user(),p))}</textarea><p class="helper" style="margin-top:12px">내 말투로 다듬고, 첫 인사와 함께 만남을 제안해 보세요.</p><div class="action-group">${btn(`${icon('heart')}만남 요청하기`,'request-opener',`data-id="${id}"`)}${btn(`${icon('copy')}문구 복사`,'copy-opener','','secondary')}${btn('AI로 새로 쓰기','ai-opener',`data-id="${id}"`,'secondary')}</div><p class="helper meeting-demo">가상 프로필과 요청·수락을 체험할 수 있어요. 실제 메시지는 전송되지 않아요.</p></div>`);}

function showAI(kind,id,context={}){if(!['reason','opener','avatar'].includes(kind))return;if(kind!=='avatar'&&!state.profile){toast('먼저 내 성향을 알려주세요.');startSurvey();return;}aiContext={kind,person:personById(id)||null,user:structuredClone(user()),context};aiBusy=false;const title={reason:'우리의 공통점을 더 읽어볼게요',opener:'내 취향에서 시작하는 첫 인사',avatar:'나만의 데이트 브리핑'}[kind];showModal(`<div class="modal-inner">${modalHead(title,'선택한 답과 직접 적은 이야기를 바탕으로 작성해요.')}<div class="ai-state"><div class="ai-label">${icon('lock')}이 기기에서 실행하는 생성형 AI</div><p>처음에는 AI 모델을 내려받아요. 수백 MB의 데이터와 여유 메모리가 필요하며, 몇 분 걸릴 수 있어요. Wi-Fi와 PC의 최신 Chrome·Edge 사용을 권장해요.</p><p style="margin-top:10px">응답 내용은 AI 서버로 보내지 않아요. 준비 중에도 취소할 수 있어요.</p><button class="btn primary" id="ai-start" data-action="run-ai">모델 다운로드 후 생성하기</button><button class="text-button" id="ai-cancel" data-action="cancel-ai" hidden>취소</button><progress class="ai-progress" id="ai-progress" max="100" value="0" hidden aria-label="AI 모델 준비 진행률"></progress><p id="ai-status" class="helper" role="status" style="margin-top:12px"></p></div><div class="ai-output" id="ai-output" role="status"></div><p id="ai-error" class="error-message" role="alert"></p><div id="ai-done" hidden><p class="helper" style="margin-top:14px">AI가 생성한 제안이에요. 응답을 잘못 해석할 수 있으니 내 생각과 맞는지 확인해 주세요.</p><div class="action-group">${btn(kind==='opener'?'문구 복사':'노트 복사','copy-ai','','secondary')}${kind==='opener'?btn('이 문구로 만남 요청하기','request-ai',`data-id="${id}"`):''}</div></div>${kind==='opener'?btn('첫 대화로 돌아가기','opener',`data-id="${id}"`,'secondary small'):''}</div>`);}
async function runAI(){if(aiBusy||!aiContext)return;aiBusy=true;const context=aiContext;document.getElementById('ai-start').disabled=true;document.getElementById('ai-start').textContent='AI 준비 중';document.getElementById('ai-cancel').hidden=false;document.getElementById('ai-progress').hidden=false;document.getElementById('ai-error').textContent='';document.getElementById('ai-output').textContent='';document.getElementById('ai-done').hidden=true;
  try{const output=await generate(context.kind,context.user,context.person,(n,text)=>{if(aiContext!==context||!modal.open)return;const el=document.getElementById('ai-progress');if(el)el.value=n;const status=document.getElementById('ai-status');if(status)status.textContent=`${text}${n>0&&n<100?` (${n}%)`:''}`;},context.context);if(aiContext===context&&modal.open&&document.getElementById('ai-output')){document.getElementById('ai-output').textContent=output;document.getElementById('ai-status').textContent='생성형 AI가 작성했어요.';document.getElementById('ai-done').hidden=false;}}
  catch(error){if(aiContext===context&&modal.open&&document.getElementById('ai-error'))document.getElementById('ai-error').textContent=error.message==='CANCELLED'?'AI 생성을 취소했어요.':error.message;}
  finally{aiBusy=false;const b=document.getElementById('ai-start');if(b&&aiContext===context){b.disabled=false;b.textContent='다시 생성하기';document.getElementById('ai-cancel').hidden=true;document.getElementById('ai-progress').hidden=true;document.getElementById('ai-status').textContent=document.getElementById('ai-output').textContent?'생성형 AI가 작성했어요.':'';}}
}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('복사했어요. 내 말투로 한 번 더 다듬어 보세요.');}catch{toast('자동 복사가 어려워요. 문구를 직접 선택해서 복사해 주세요.');}}
function about(){showModal(`<div class="modal-inner">${modalHead('전북에서, 일상을 나누는 만남')}<p class="body-copy">전북 잇음은 지역 안에서 서로의 생활이 맞는 사람을 발견하도록 돕는 소개팅 서비스의 체험 버전이에요.</p><section class="detail-section"><h3>추천은 어떻게 달라지나요?</h3><p class="helper">설문의 같은 응답, 공통 관심사, 겹치는 생활권과 시간을 비교해 순서를 정해요. 특히 실제로 만날 수 있는 지역과 시간에 비중을 두어요. 사람의 신뢰도나 연애 성공률을 점수로 매기지 않아요.</p></section><section class="detail-section"><h3>AI는 무엇을 하나요?</h3><p class="helper">오픈소스 WebLLM과 Qwen3 모델을 브라우저에서 실행해 공통점 설명, 첫 대화 문구와 프리미엄 아바타 브리핑을 새로 작성해요. 기본 추천과 설문 요약은 비교 규칙으로 동작하며, 생성형 AI와 구분해 표시해요.</p></section><section class="detail-section"><h3>체험 정보는 어디에 저장되나요?</h3><p class="helper">추천되는 프로필은 가상 인물이에요. 직접 올린 내 사진은 이 브라우저에만 저장돼요. 설문, 관심 목록, 만남 요청과 약속 초안은 이 기기의 브라우저에만 저장돼요. 만남 요청·수락·거절은 같은 기기에서 가상 상대와 체험해요. 실제 회원 가입·본인 인증·메시지 전송·예약 기능은 포함하지 않아요.</p></section><div class="modal-footer">${btn('확인했어요','close')}</div></div>`);}
document.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const a=target.dataset.action,id=target.dataset.id;
  if(meetings.handleAction(a,target)||features.handleAction(a,target))return;
  switch(a){
    case 'navigate':navigate(target.dataset.view);break;
    case 'close':closeModal();break;
    case 'survey':startSurvey();break;
    case 'survey-next':nextSurvey();break;
    case 'survey-back':collectSurvey();surveyStep=Math.max(0,surveyStep-1);showSurvey();break;
    case 'survey-choice':{const k=target.dataset.key,v=target.dataset.value,selected=draft[k].includes(v);if(selected){draft[k]=draft[k].filter(x=>x!==v);}else{if(draft[k].length>=Number(target.dataset.max)){toast(`최대 ${target.dataset.max}개까지 선택할 수 있어요.`);break;}draft[k].push(v);}target.classList.toggle('selected',!selected);target.setAttribute('aria-pressed',String(!selected));break;}
    case 'answer':draft.answers[target.dataset.key]=Number(target.dataset.value);target.parentElement.querySelectorAll('button').forEach(b=>{const selected=b===target;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});break;
    case 'filter-gender':filters.gender=target.dataset.value;render();break;
    case 'filter-time':filters.sameTime=!filters.sameTime;render();break;
    case 'filters':showFilters();break;
    case 'reset-filters':filters={city:'전체',gender:'all',minAge:19,maxAge:99,sameTime:false,sameArea:false};closeModal();render();break;
    case 'apply-filters':{const min=Number(document.getElementById('min-age').value),max=Number(document.getElementById('max-age').value);if(!Number.isInteger(min)||!Number.isInteger(max)||min<19||max>99||min>max){document.getElementById('filter-error').textContent='19~99세 사이에서 최소 나이가 최대 나이보다 작거나 같도록 입력해 주세요.';break;}filters={...filters,city:document.getElementById('filter-city').value,minAge:min,maxAge:max,sameTime:document.getElementById('same-time').checked,sameArea:document.getElementById('same-area').checked};closeModal();render();break;}
    case 'detail':showDetail(id);break;
    case 'like':toggleLike(id);break;
    case 'hide':if(personById(id)){state.hidden=[...new Set([...state.hidden,id])];persist();closeModal();render();toast('추천에서 숨겼어요. 내 프로필에서 다시 표시할 수 있어요.');}break;
    case 'restore-hidden':state.hidden=[];persist();render();toast('숨긴 프로필을 다시 표시했어요.');break;
    case 'opener':if(aiBusy){cancelAI();aiBusy=false;}aiContext=null;showOpener(id);break;
    case 'copy-opener':copy(document.getElementById('opener-text').value);break;
    case 'copy-ai':copy(document.getElementById('ai-output').textContent);break;
    case 'ai-reason':showAI('reason',id);break;
    case 'ai-opener':openerDrafts.set(id,document.getElementById('opener-text').value);showAI('opener',id);break;
    case 'request-opener':{const message=document.getElementById('opener-text').value;openerDrafts.set(id,message);meetings.showForm(id,message);break;}
    case 'request-ai':{const message=document.getElementById('ai-output').textContent;if(message){openerDrafts.set(id,message);meetings.showForm(id,message);}break;}
    case 'run-ai':runAI();break;
    case 'cancel-ai':cancelAI();break;
    case 'remove-plan':state.plans.splice(Number(target.dataset.index),1);persist();render();toast('약속 초안을 삭제했어요.');break;
    case 'about':about();break;
    case 'reset-confirm':showModal(`<div class="modal-inner">${modalHead('이 기기의 체험 정보를 지울까요?','사진, MBTI, 설문, 관심 목록, 저장 코스, 만남 요청과 축제 알림이 지워져요. 다시 작성해 시작할 수 있어요.')}<div class="modal-footer">${btn('돌아가기','close','','secondary')}${btn('초기화','reset-state')}</div></div>`);break;
    case 'reset-state':if(!meetings.reset())break;openerDrafts.clear();features.reset();state={profile:null,likes:[],hidden:[],plans:[]};persist();closeModal();navigate('discover');toast('체험 정보를 초기화했어요.');break;
  }
});
document.addEventListener('change',e=>{features.handleChange(e.target);if(e.target.id==='my-city'&&draft){const value=e.target.value;draft.city=value;if(!draft.areas.includes(value)){if(draft.areas.length>=3)draft.areas.pop();draft.areas.unshift(value);}modal.querySelectorAll('[data-key="areas"]').forEach(b=>{const on=draft.areas.includes(b.dataset.value);b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});}});
window.addEventListener('hashchange',()=>{view=NAV.some(n=>n.id===location.hash.slice(1))?location.hash.slice(1):'discover';render();window.scrollTo({top:0,behavior:'instant'});});
render();
