import { CITIES, TIMES, INTERESTS, QUESTIONS, SAMPLE_USER } from './data.js';
import { readState, saveState, normalizeProfile, profileSummary, recommend, draftOpener, escapeHTML as esc } from './core.js';

const storage={getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)};
const ROOT_ID='ieum-experience-root';
let draft=null, step=0, dateChoice=null;
const steps=['basics','city','areas','times','interests','seeking',...QUESTIONS.map(q=>q.id),'note'];

function root(){let el=document.getElementById(ROOT_ID);if(!el){el=document.createElement('div');el.id=ROOT_ID;document.body.appendChild(el);}return el;}
function lock(on){document.documentElement.classList.toggle('ieum-locked',on);document.body.classList.toggle('ieum-locked',on);}
function closeFlow(){root().innerHTML='';lock(false);}
function stateNow(){return readState(storage);}
function defaultDraft(){const p=stateNow().profile;return p?structuredClone(p):{name:'',age:25,city:'전주',areas:['전주'],times:[],interests:[],seeking:'all',answers:{},note:''};}
function progress(){return Math.max(6,Math.round(((step+1)/steps.length)*100));}
function shell(body,{title='내 잇음 찾기',back=true,close=true}={}){return `<div class="ix-overlay"><div class="ix-shell"><header class="ix-topbar">${back?'<button class="ix-icon" data-ix="back" aria-label="이전">←</button>':'<span class="ix-icon ghost"></span>'}<strong>${title}</strong>${close?'<button class="ix-icon" data-ix="close" aria-label="닫기">×</button>':'<span class="ix-icon ghost"></span>'}</header><div class="ix-progress"><span style="width:${progress()}%"></span></div><main class="ix-main">${body}</main></div></div>`;}
function choiceList(items,selected=[],attr='value'){return `<div class="ix-choices">${items.map(item=>{const value=typeof item==='string'?item:item.value;const label=typeof item==='string'?item:item.label;const on=selected.includes(value);return `<button class="ix-choice ${on?'selected':''}" data-ix="choose" data-${attr}="${esc(value)}" aria-pressed="${on}"><span>${esc(label)}</span><b>${on?'✓':'›'}</b></button>`;}).join('')}</div>`;}
function renderStep(){const key=steps[step];let body='';
  if(key==='basics') body=`<section class="ix-copy"><span>1분이면 충분해요</span><h1>어떻게 불러드릴까요?</h1><p>실명 대신 닉네임을 써도 괜찮아요.</p></section><div class="ix-fields"><label>닉네임<input id="ix-name" maxlength="16" autocomplete="off" value="${esc(draft.name)}" placeholder="예: 진표"></label><label>나이<input id="ix-age" type="number" min="19" max="45" value="${draft.age||25}"></label></div><p class="ix-error" id="ix-error"></p><button class="ix-next" data-ix="next">다음</button>`;
  else if(key==='city') body=`<section class="ix-copy"><span>생활권부터 볼게요</span><h1>평소 가장 많이 있는 곳은?</h1><p>정확한 주소 대신 시·군 단위만 사용해요.</p></section>${choiceList(CITIES,[draft.city],'city')}`;
  else if(key==='areas') body=`<section class="ix-copy"><span>실제로 만날 수 있는 거리</span><h1>자주 오갈 수 있는 곳을 골라주세요.</h1><p>최대 3곳. ${esc(draft.city)}은 기본으로 포함돼요.</p></section>${choiceList(CITIES,draft.areas,'area')}<p class="ix-error" id="ix-error"></p><button class="ix-next" data-ix="next">이대로 계속</button>`;
  else if(key==='times') body=`<section class="ix-copy"><span>매칭보다 중요한 것</span><h1>언제 만나는 게 가장 편해요?</h1><p>최대 2개만 골라주세요. 실제 약속 가능한 사람을 먼저 찾을게요.</p></section>${choiceList(TIMES,draft.times,'time')}<p class="ix-error" id="ix-error"></p><button class="ix-next" data-ix="next">다음</button>`;
  else if(key==='interests') body=`<section class="ix-copy"><span>대화가 시작되는 취향</span><h1>같이 나누고 싶은 건?</h1><p>2~5개만 고르면 충분해요.</p></section><div class="ix-pills">${INTERESTS.map(v=>`<button class="ix-pill ${draft.interests.includes(v)?'selected':''}" data-ix="interest" data-value="${esc(v)}" aria-pressed="${draft.interests.includes(v)}">${esc(v)}</button>`).join('')}</div><p class="ix-error" id="ix-error"></p><button class="ix-next" data-ix="next">다음</button>`;
  else if(key==='seeking') body=`<section class="ix-copy"><span>추천 범위</span><h1>누구를 소개받고 싶어요?</h1><p>언제든 내 프로필에서 바꿀 수 있어요.</p></section>${choiceList([{value:'woman',label:'여성'},{value:'man',label:'남성'},{value:'all',label:'성별 상관없어요'}],[draft.seeking],'seeking')}`;
  else if(QUESTIONS.some(q=>q.id===key)){const q=QUESTIONS.find(q=>q.id===key);const idx=QUESTIONS.indexOf(q)+1;body=`<section class="ix-copy"><span>관계 성향 ${idx} / ${QUESTIONS.length}</span><h1>${esc(q.title)}</h1><p>정답은 없어요. 지금의 나와 가까운 쪽을 골라주세요.</p></section><div class="ix-choices">${q.options.map((label,i)=>`<button class="ix-choice ${draft.answers[q.id]===i?'selected':''}" data-ix="answer" data-q="${q.id}" data-index="${i}"><span>${esc(label)}</span><b>${draft.answers[q.id]===i?'✓':'›'}</b></button>`).join('')}</div>`;}
  else body=`<section class="ix-copy"><span>마지막이에요</span><h1>상대가 알았으면 하는 게 있나요?</h1><p>없다면 비워둬도 돼요. 추천을 더 자연스럽게 설명할 때 참고해요.</p></section><textarea class="ix-note" id="ix-note" maxlength="300" placeholder="예: 처음에는 조금 낯을 가리지만 친해지면 말이 많아요.">${esc(draft.note||'')}</textarea><button class="ix-next" data-ix="finish">내 잇음 만들기</button>`;
  root().innerHTML=shell(body,{back:step>0}); lock(true); setTimeout(()=>document.getElementById('ix-name')?.focus(),20);
}
function error(message){const el=document.getElementById('ix-error');if(el)el.textContent=message;}
function collectBasics(){const name=document.getElementById('ix-name')?.value.trim();const age=Number(document.getElementById('ix-age')?.value);if(!name){error('닉네임을 입력해주세요.');return false;}if(!Number.isInteger(age)||age<19||age>45){error('나이는 19~45세로 입력해주세요.');return false;}draft.name=name;draft.age=age;return true;}
function next(){const key=steps[step];if(key==='basics'&&!collectBasics())return;if(key==='areas'&&draft.areas.length<1){error('생활권을 한 곳 이상 골라주세요.');return;}if(key==='times'&&draft.times.length<1){error('가능한 시간을 한 개 이상 골라주세요.');return;}if(key==='interests'&&draft.interests.length<2){error('취향을 두 개 이상 골라주세요.');return;}step=Math.min(step+1,steps.length-1);renderStep();}
function openOnboarding(){draft=defaultDraft();step=0;renderStep();}
function finish(){draft.note=document.getElementById('ix-note')?.value.trim()||'';draft.areas=[...new Set([draft.city,...draft.areas])].slice(0,3);const profile=normalizeProfile(draft);if(!profile){error('입력한 내용을 다시 확인해주세요.');return;}const s=stateNow();s.profile=profile;saveState(storage,s);renderResult(profile,s);}
function renderResult(profile,s){const summary=profileSummary(profile);const matches=recommend(profile,{hidden:s.hidden}).slice(0,3);const top=matches[0];const topHtml=top?`<div class="ix-match"><div class="ix-avatar portrait-bg p${top.person.photo}"></div><div><small>가장 먼저 이어질 사람</small><strong>${esc(top.person.name)} · ${top.person.age}</strong><p>${esc(top.person.city)} · ${esc(top.person.job)}</p></div><b>${top.score}</b></div>`:'';root().innerHTML=shell(`<section class="ix-result"><div class="ix-check">✓</div><span>추천 준비 완료</span><h1>${esc(profile.name)} 님은<br><strong>${esc(summary.title)}</strong>에 가까워요.</h1><p>${esc(summary.body)}</p><div class="ix-tagline">${summary.tags.slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div>${topHtml}<button class="ix-next" data-ix="result-home">오늘의 3명 보기</button><button class="ix-sub" data-ix="date">바로 첫 약속 만들기</button></section>`,{title:'내 잇음 카드',back:false});lock(true);}

function routeFor(city){const map={전주:'객리단길 카페 → 전주천 산책',군산:'월명동 카페 → 근대역사거리 산책',익산:'영등동 카페 → 중앙체육공원 산책',완주:'삼례 카페 → 삼례문화예술촌 산책',정읍:'시내 카페 → 정읍천 산책',남원:'광한루원 근처 카페 → 요천 산책'};return map[city]||`${city} 중심가 카페 → 가까운 산책 코스`;}
function openDate(){const s=stateNow();if(!s.profile){openOnboarding();return;}const matches=recommend(s.profile,{hidden:s.hidden}).slice(0,3);if(!matches.length){return;}dateChoice=matches[0].person.id;renderDate(matches,s.profile);}
function renderDate(matches,profile){const m=matches.find(x=>x.person.id===dateChoice)||matches[0];dateChoice=m.person.id;const city=m.areas[0]||profile.city;const time=m.times[0]||profile.times[0]||'토요일 오후';const route=routeFor(city);root().innerHTML=shell(`<section class="ix-copy"><span>첫 약속도 한 번에</span><h1>누구와 만나볼까요?</h1><p>생활권과 가능한 시간을 먼저 맞춰서, 부담 없는 초안을 만들었어요.</p></section><div class="ix-date-people">${matches.map(x=>`<button class="ix-person ${x.person.id===dateChoice?'selected':''}" data-ix="date-person" data-id="${x.person.id}"><div class="ix-person-photo portrait-bg p${x.person.photo}"></div><span>${esc(x.person.name)}<small>${x.person.age}</small></span><b>${x.score}</b></button>`).join('')}</div><div class="ix-date-card"><div><small>추천 시간</small><strong>${esc(time)}</strong></div><div><small>만남 생활권</small><strong>${esc(city)}</strong></div><div class="wide"><small>가벼운 첫 코스 · 약 90분</small><strong>${esc(route)}</strong><p>오래 머무는 약속보다 대화를 시작하기 쉬운 공개된 장소 위주로 잡았어요.</p></div></div><button class="ix-next" data-ix="save-date" data-city="${esc(city)}" data-time="${esc(time)}">이 약속 제안 준비하기</button><button class="ix-sub" data-ix="close">아직은 둘러볼게요</button>`,{title:'첫 잇음 준비',back:false});lock(true);}
function saveDate(city,time){const s=stateNow();const p=s.profile;const matches=recommend(p,{hidden:s.hidden}).slice(0,3);const m=matches.find(x=>x.person.id===dateChoice)||matches[0];if(!m)return;const plan={personId:m.person.id,city,time};if(!s.plans.some(x=>x.personId===plan.personId&&x.city===city&&x.time===time))s.plans.unshift(plan);s.plans=s.plans.slice(0,20);saveState(storage,s);const opener=draftOpener(p,m.person);root().innerHTML=shell(`<section class="ix-result compact"><div class="ix-check">✓</div><span>첫 약속 초안 저장</span><h1>${esc(m.person.name)} 님과<br>이제 대화만 시작하면 돼요.</h1><div class="ix-confirm"><small>${esc(city)} · ${esc(time)}</small><strong>${esc(routeFor(city))}</strong></div><div class="ix-message"><small>첫 메시지 추천</small><p id="ix-opener">${esc(opener)}</p><button data-ix="copy">문구 복사</button></div><button class="ix-next" data-ix="result-home">홈으로 돌아가기</button><button class="ix-sub" data-ix="old-date">저장한 약속 자세히 보기</button></section>`,{title:'약속 준비 완료',back:false});lock(true);}

root().addEventListener('click',e=>{const t=e.target.closest('[data-ix]');if(!t)return;const a=t.dataset.ix;
  if(a==='close'){closeFlow();return;}if(a==='back'){if(step>0){step--;renderStep();}else closeFlow();return;}if(a==='next'){next();return;}if(a==='finish'){finish();return;}
  if(a==='choose'){const key=steps[step];if(key==='city'){draft.city=t.dataset.city;draft.areas=[...new Set([draft.city,...draft.areas])].slice(0,3);setTimeout(next,140);}else if(key==='areas'){const v=t.dataset.area;if(v===draft.city)return;draft.areas=draft.areas.includes(v)?draft.areas.filter(x=>x!==v):draft.areas.length<3?[...draft.areas,v]:draft.areas;renderStep();}else if(key==='times'){const v=t.dataset.time;draft.times=draft.times.includes(v)?draft.times.filter(x=>x!==v):draft.times.length<2?[...draft.times,v]:draft.times;renderStep();}else if(key==='seeking'){draft.seeking=t.dataset.seeking;setTimeout(next,140);}return;}
  if(a==='interest'){const v=t.dataset.value;draft.interests=draft.interests.includes(v)?draft.interests.filter(x=>x!==v):draft.interests.length<5?[...draft.interests,v]:draft.interests;renderStep();return;}
  if(a==='answer'){draft.answers[t.dataset.q]=Number(t.dataset.index);setTimeout(next,140);return;}
  if(a==='result-home'){location.hash='#discover';location.reload();return;}if(a==='date'){openDate();return;}if(a==='date-person'){dateChoice=t.dataset.id;const s=stateNow();renderDate(recommend(s.profile,{hidden:s.hidden}).slice(0,3),s.profile);return;}
  if(a==='save-date'){saveDate(t.dataset.city,t.dataset.time);return;}if(a==='copy'){const text=document.getElementById('ix-opener')?.textContent||'';navigator.clipboard?.writeText(text);t.textContent='복사했어요';return;}if(a==='old-date'){closeFlow();location.hash='#dates';return;}
});

document.addEventListener('click',e=>{const survey=e.target.closest('[data-action="survey"]');const date=e.target.closest('[data-action="navigate"][data-view="dates"],a[href="#dates"]');if(survey){e.preventDefault();e.stopImmediatePropagation();openOnboarding();return;}if(date){e.preventDefault();e.stopImmediatePropagation();openDate();}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&root().innerHTML)closeFlow();});
