import { CITIES, PEOPLE } from './data.js?v=ieum5';
import { recommend, match, escapeHTML as esc } from './core.js?v=ieum5';
import { icon } from './icons.js?v=ieum5';
import { ROUTES, FESTIVALS, GUIDE_CHECKED, mapURL } from './local-guide.js?v=ieum5';
import { MBTIS, readExtra, saveExtra, normalizePlan, normalizeMBTI, routesFor, routeForPlan, festivalsOn, koreaToday, itinerary, planKey, routeText, coachPlan, canUseAvatar, upcomingFestivals, festivalStatus, festivalICS, EXTRA_KEY, LEGACY_EXTRA_KEY } from './experience-core.js?v=ieum5';
import { preparePhoto } from './profile-media.js?v=ieum5';

export function createFeatures({ storage, state, user, render, navigate, showModal, modalHead, btn, toast, showAI, copy, intro, meetingPanel }) {
  let extra=readExtra(storage), planner={...extra.planner}, tone='warm', scenario='open', festivalCity='전체', dateFestivalCity='전체', onlySaved=false, photoBusy=false;
  const option=(items,selected)=>items.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('');
  const link=(label,query,cls='text-button')=>`<a class="${cls}" href="${esc(mapURL(query))}" target="_blank" rel="noopener noreferrer">${label}${icon('arrow')}</a>`;
  const route=()=>routeForPlan(planner);
  const people=()=>{const list=recommend(user(),{hidden:state().hidden}).map(m=>m.person);const selected=PEOPLE.find(p=>p.id===planner.personId&&!state().hidden.includes(p.id));if(selected&&!list.some(p=>p.id===selected.id))list.push(selected);return list;};
  function person(){const list=people();return list.find(p=>p.id===planner.personId)||list.find(p=>state().likes.includes(p.id))||list[0];}
  function persist(){extra.planner={...planner};const ok=saveExtra(storage,extra);if(!ok)toast('저장 공간이 부족해요. 이 화면에서는 사용할 수 있지만 새로고침하면 사라질 수 있어요.');return ok;}
  function switchCity(city){planner=normalizePlan({...planner,city,routeId:'',movie:false});persist();}
  function avatar(cls='small-avatar'){return `<div class="${cls}">${extra.photo?`<img src="${extra.photo}" alt="내 프로필 사진">`:icon('user')}</div>`;}
  function compactPremium(){return `<section class="side-panel premium-teaser"><span class="premium-label">잇음 Premium</span><h3>떨리는 첫 만남,<br>옆에서 도와줄게요.</h3><p>데이트 코스부터 다음 한마디까지.<br>나만의 아바타 코치와 준비해요.</p>${btn(`아바타 모드 ${icon('arrow')}`,'avatar','','secondary block')}</section>`;}
  function compactFestival(){const f=upcomingFestivals()[0];return f?`<section class="side-panel side-festival"><div class="side-heading"><h2>다가오는 지역 축제</h2>${icon('calendar')}</div><span class="festival-status">${festivalStatus(f)}</span><h3>${esc(f.name)}</h3><p>${shortDate(f.start)} — ${shortDate(f.end)} · ${esc(f.city)}</p><button class="text-button" data-action="festivals">다른 축제도 보기 ${icon('arrow')}</button></section>`:'';}
  function shortDate(date){return `${Number(date.slice(5,7))}.${Number(date.slice(8,10))}`;}
  function profileCard(){return `<section class="content-panel profile-identity"><div class="profile-photo-row">${avatar('own-photo')}<div class="photo-copy"><span class="source-tag">내 프로필</span><h2>${state().profile?`${esc(user().name)} <span>${user().age}</span>`:'나를 보여주는 한 장'}</h2><p>${state().profile?`${esc(user().city)} · ${extra.mbti||'MBTI 미설정'}`:'사진과 MBTI부터 가볍게 채워보세요.'}</p><div class="photo-actions"><label class="btn secondary small upload-label" for="profile-photo">${icon('camera')}${extra.photo?'사진 변경':'사진 추가'}</label>${extra.photo?'<button class="text-button" data-action="remove-photo">삭제</button>':''}</div></div></div><input class="visually-hidden" id="profile-photo" type="file" accept="image/jpeg,image/png,image/webp" aria-label="프로필 사진 업로드"><p class="helper photo-help" id="photo-status" role="status">JPG·PNG·WebP, 최대 10MB. 가운데를 정사각형으로 잘라 이 기기에 저장해요.</p><div class="mbti-row"><div><label for="my-mbti">나의 MBTI</label><p>나를 소개하는 가벼운 대화 소재</p></div><select id="my-mbti"><option value="">아직 몰라요</option>${option(MBTIS,extra.mbti)}</select></div><p class="helper">직접 선택한 MBTI예요. 추천 순위나 궁합 점수에는 사용하지 않아요.</p></section>`;}
  function membership(){return `<section class="content-panel membership-row"><div><span class="premium-label">잇음 Premium</span><h3>${extra.trial?'아바타 모드를 체험 중이에요':'첫 만남을 준비하는 나만의 코치'}</h3><p class="helper">${extra.trial?'결제 없는 기능 체험 · 언제든 종료할 수 있어요.':'상대별 데이트 제안, 추천 멘트, 답변 상황별 대화 연습'}</p></div>${btn(extra.trial?'체험 관리':'자세히 보기','premium','','secondary small')}</section>`;}
  function festivalCard(f){const saved=extra.festivals.includes(f.id);return `<article class="festival-card"><div class="festival-date"><span>${Number(f.start.slice(5,7))}월</span><b>${Number(f.start.slice(8,10))}</b></div><div class="festival-copy"><div class="festival-meta">${esc(f.city)}<span class="festival-status">${festivalStatus(f)}</span></div><h3>${esc(f.name)}</h3><p>${f.start.slice(0,4)}. ${shortDate(f.start)} — ${shortDate(f.end)}</p><p class="helper">${esc(f.place)}</p><div class="festival-actions"><button class="text-button ${saved?'accent':''}" data-action="save-festival" data-id="${f.id}" aria-pressed="${saved}" aria-label="${esc(f.name)} ${saved?'알림 보관 취소':'알림 보관'}">${icon(saved?'check':'bell')}${saved?'보관 중':'알림 보관'}</button><button class="text-button" data-action="festival-calendar" data-id="${f.id}">${icon('calendar')}달력에 추가</button></div><div class="festival-links"><button class="text-button" data-action="festival-route" data-id="${f.id}">축제 날짜로 코스 보기 ${icon('arrow')}</button><a class="text-button" href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">공식 일정 ${icon('external')}</a></div></div></article>`;}
  function festivalsModal(){const all=upcomingFestivals(festivalCity), list=onlySaved?all.filter(f=>extra.festivals.includes(f.id)):all;showModal(`<div class="modal-inner festival-modal">${modalHead('다가오는 지역 축제','함께 가고 싶은 날을 미리 담아두세요.')}<div class="festival-filter"><div class="field"><label for="festival-city">축제 지역</label><select id="festival-city">${option(['전체',...CITIES],festivalCity)}</select></div><label class="check-row"><input id="festival-saved-only" type="checkbox" ${onlySaved?'checked':''}>보관한 축제만</label></div><div class="calendar-note">${icon('bell')}<p>알림 보관 후 이곳에서 다시 확인해요.<br><b>달력에 추가</b>하면 시작 하루 전 알림도 함께 가져가요.</p></div>${list.length?list.map(festivalCard).join(''):`<div class="compact-empty"><h3>${onlySaved?'보관한 예정 축제가 없어요':'확인된 예정 축제가 없어요'}</h3><p>다른 지역의 축제를 둘러보세요.</p></div>`}<p class="helper source-foot">${GUIDE_CHECKED} 공식 발표·한국관광공사 일정 확인. 일정은 바뀔 수 있어요. 달력 앱에서 파일을 가져오고 알림을 허용해 주세요.</p></div>`);}
  function festivalStrip(){
    const list=upcomingFestivals(dateFestivalCity);
    return `<section class="content-panel date-festivals" aria-labelledby="date-festival-title">
      <div class="section-header"><div><span class="source-tag">함께 가면 더 좋은 날</span><h2 id="date-festival-title">다가오는 지역 축제</h2><p class="helper">축제가 열리는 날에 맞춰 특별한 데이트를 준비해 보세요.</p></div><div class="field"><label for="date-festival-city">축제 둘러볼 지역</label><select id="date-festival-city">${option(['전체',...CITIES],dateFestivalCity)}</select></div></div>
      ${list.length?`<div class="festival-rail">${list.map(f=>`<article class="festival-preview"><div class="festival-meta">${esc(f.city)}<span class="festival-status">${festivalStatus(f)}</span></div><h3>${esc(f.name)}</h3><p>${f.start.slice(0,4)}. ${shortDate(f.start)} — ${shortDate(f.end)}</p><small>${esc(f.place)}</small><button class="btn secondary small" data-action="festival-route" data-id="${f.id}">축제 날짜로 코스 보기 ${icon('arrow')}</button><a class="text-button" href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">공식 일정 ${icon('external')}</a></article>`).join('')}</div>`:'<p class="helper festival-empty">이 지역에 확인된 예정 축제가 없어요. 전체 지역을 선택해 다른 축제도 둘러보세요.</p>'}
      <button class="text-button accent" data-action="festivals">축제 전체 보기 · 알림 보관 ${icon('arrow')}</button>
    </section>`;
  }
  function routeOption(r,selected){return `<button class="route-option ${r.festivalId?'festival-route-option':''} ${r.id===selected?'selected':''}" data-action="choose-route" data-id="${r.id}" aria-pressed="${r.id===selected}"><span>${esc(r.mood)}</span><b>${esc(r.title)}</b><small>${esc(r.sight)}</small>${icon(r.id===selected?'check':'arrow')}</button>`;}
  function dates(){
    const p=person();
    const head=intro('데이트','만나는 곳부터, 마지막 산책까지.','우리 동네에서 시작하는 두 사람의 하루.',`<div class="action-group">${btn('만남 요청함','meetings','','secondary small')}${p?btn(`${icon('chat')}아바타 모드`,'avatar','','secondary small'):''}</div>`);
    if(!p)return `${head}${meetingPanel()}${festivalStrip()}<div class="wide-panel"><div class="compact-empty"><h2>선택할 수 있는 프로필이 없어요</h2><p>숨긴 프로필을 다시 표시해 보세요.</p>${btn('숨긴 프로필 다시 보기','restore-hidden')}</div></div>`;
    planner.personId=p.id;
    const r=route(), list=routesFor(planner.city,planner.date), matching=list.filter(r=>r.festivalId), m=match(user(),p), steps=itinerary(planner);
    const total=steps.reduce((sum,s)=>sum+s.minutes,0), hrs=Math.floor(total/60), mins=total%60;
    return `${head}${meetingPanel()}${festivalStrip()}<div class="date-layout"><div class="date-main">
      <section class="content-panel route-builder" id="date-route-builder"><div class="section-header"><div><span class="source-tag">01 · 두 사람의 약속</span><h2>누구와, 어디에서 만날까요?</h2></div></div>
        <div class="planner-selects"><div class="field"><label for="date-person">함께 만나보고 싶은 사람</label><select id="date-person">${people().map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)} · ${x.age} · ${esc(x.city)}</option>`).join('')}</select></div><div class="field"><label for="date-city">데이트 지역</label><select id="date-city">${option(CITIES,planner.city)}</select></div></div>
        <p class="helper overlap-note">${m.areas.includes(planner.city)?`${esc(planner.city)}은 두 사람의 생활권이 겹쳐요.`:'선택한 지역까지 이동이 괜찮은지 먼저 이야기해 보세요.'}${!state().profile?' 내 취향은 예시 기준이에요.':''}</p>
        <div class="planner-selects timing-fields"><div class="field"><label for="plan-date">날짜 <span class="helper">선택</span></label><input id="plan-date" type="date" value="${planner.date}"></div><div class="field"><label for="plan-start">만나는 시간</label><input id="plan-start" type="time" value="${planner.start}" required></div></div>
        <div class="route-options" role="group" aria-label="지역별 데이트 코스">${list.filter(r=>!r.festivalId).map(x=>routeOption(x,r.id)).join('')}
          <div class="festival-match-note" role="status">${matching.length?`${icon('calendar')}<div><b>이 날짜에 열리는 축제</b><p>${planner.date} · ${esc(planner.city)}의 축제를 데이트 코스로 골라보세요.</p></div>`:`${icon('calendar')}<p>${planner.date?'선택한 지역·날짜에 열리는 축제가 없어요. 일반 코스에서 골라보세요.':'날짜를 선택하면 그날 열리는 지역 축제도 추천해 드려요.'}</p>`}</div>
          ${matching.map(x=>routeOption(x,r.id)).join('')}
        </div>
        <div class="route-toggles"><label class="switch-row"><span><b>영화 한 편 추가</b><small>${r.movie?'보고 싶은 상영작을 함께 골라요':'이 코스는 야외·체험 중심이에요'}</small></span><input id="plan-movie" type="checkbox" ${planner.movie?'checked':''} ${!r.movie?'disabled':''} role="switch"></label><label class="switch-row"><span><b>숙박도 살펴보기 <em>선택</em></b><small>하루가 더 아쉽다면, 둘 다 원할 때</small></span><input id="plan-stay" type="checkbox" ${planner.stay?'checked':''} role="switch"></label></div>
      </section>
      <section class="content-panel itinerary-panel"><div class="section-header"><div><span class="source-tag">02 · 이렇게 이어가요</span><h2>${esc(r.title)}</h2></div><span class="duration">약 ${hrs}시간${mins?' '+mins+'분':''}</span></div><p class="helper">선택한 활동에 따라 바뀌는 예시 시간표예요. 이동·영업시간·상영시간은 지도에서 확인하고 조정해 주세요.</p>
        <ol class="route-timeline">${steps.map((s,i)=>`<li class="route-stop ${s.kind==='stay'?'optional-stop':''}"><div class="stop-index">${String(i+1).padStart(2,'0')}</div><div class="stop-body"><div class="stop-meta"><span>${s.at}</span><span>${s.label}</span></div><h3>${esc(s.name)}</h3><p>${esc(s.tip)}</p>${link(s.kind==='movie'?'영화관·상영 정보 찾기':s.kind==='stay'?'이 지역 숙박업소 찾기':'지도에서 보기',s.name)}${s.kind==='festival'?`<a class="text-button accent" href="${esc(r.source)}" target="_blank" rel="noopener noreferrer">축제 프로그램 확인 ${icon('external')}</a>`:''}</div></li>`).join('')}</ol>
        <div class="route-actions">${btn(`${icon('heart')}코스 저장`,'save-route')}${btn(`${icon('copy')}코스 복사`,'copy-route','','secondary')}</div><div class="route-links">${link('이 지역 카페 찾기',planner.city+' 카페')}<a class="text-button" href="${esc(r.source)}" target="_blank" rel="noopener noreferrer">지역 여행 안내 ${icon('external')}</a></div><p class="helper route-note">저장한 코스는 나만 보는 초안이에요. 실제 약속·예약은 두 사람이 함께 확정해요.</p>
      </section>${savedRoutes()}
    </div><aside class="date-sidebar"><section class="side-panel partner-summary"><div class="mini-person"><div class="mini-portrait"><div class="portrait-bg p${p.photo}" role="img" aria-label="가상의 ${esc(p.name)} 프로필 사진"></div></div><div><span class="helper">함께 준비하는 사람</span><h3>${esc(p.name)} <span>${p.age}</span></h3><p>${esc(p.city)} · ${esc(p.mbti)}</p></div></div><div class="tags">${p.interests.slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><p class="helper">${m.times.length?`겹치는 시간: ${esc(m.times.join(' · '))}`:'편한 시간대를 먼저 맞춰보세요.'}</p></section>
      <section class="side-panel premium-teaser"><span class="premium-label">이음 Premium · 아바타 모드</span><h3>첫마디가 어렵다면,<br>함께 연습해요.</h3><p>${esc(p.name)} 님의 취향과 이 코스로<br>첫 인사부터 다음 대화까지.</p>${btn(`나의 아바타 코치 ${icon('arrow')}`,'avatar','','primary block')}<small>추천 멘트 · 답변 상황별 연습</small></section><section class="side-panel route-tip"><h3>좋은 계획에도 여백은 필요하니까.</h3><p>모든 장소를 다 들르지 않아도 괜찮아요. 커피 한 잔이 좋았다면, 다음 만남을 남겨두세요.</p></section>
    </aside></div>`;
  }
  function savedRoutes(){if(!extra.routes.length&&!state().plans.length)return '';return `<section class="content-panel saved-routes"><div class="section-header"><h2>저장한 데이트 코스 <span class="count">${extra.routes.length+state().plans.length}</span></h2></div>${extra.routes.map((p,i)=>`<div class="saved-route"><div><b>${esc(PEOPLE.find(x=>x.id===p.personId).name)} 님과 ${esc(p.city)}에서</b><p>${esc(routeForPlan(p).title)}</p><small>${p.date||'날짜 미정'} · ${p.start}${p.movie?' · 영화 포함':''}${p.stay?' · 숙박 선택':''}</small></div><div class="saved-actions"><button class="text-button accent" data-action="load-route" data-index="${i}">불러오기</button><button class="text-button" data-action="remove-route" data-index="${i}" aria-label="${i+1}번 코스 삭제">삭제</button></div></div>`).join('')}${state().plans.map((p,i)=>`<div class="saved-route"><div><b>${esc(PEOPLE.find(x=>x.id===p.personId).name)} 님과 ${esc(p.city)}에서</b><p>${esc(p.time)} · 이전에 저장한 커피와 산책</p></div><button class="text-button" data-action="remove-plan" data-index="${i}">삭제</button></div>`).join('')}</section>`;}
  function premiumModal(){showModal(`<div class="modal-inner premium-modal">${modalHead('나의 아바타 모드','쑥스러운 마음은 그대로, 준비는 조금 더 편하게.')}<span class="premium-label">잇음 Premium</span><h3 class="premium-title">AI가 곁에서,<br>데이트를 함께 준비해요.</h3><p class="body-copy">상대의 취향을 읽고, 내가 할 말과 이어질 대화를 미리 연습해요. 마지막 선택은 언제나 나답게.</p><div class="plan-comparison"><div><span>잇음 Basic</span><b>무료</b><p>오늘의 잇음 · 관심 저장<br>지역별 데이트 · 축제 알림<br>프로필 · MBTI</p></div><div class="selected"><span>잇음 Premium</span><b>월 9,900원 <small>출시 예정 요금안</small></b><p>상대별 아바타 코치<br>추천 멘트 · 후속 대화 연습<br>생성형 AI 맞춤 데이트 브리핑</p></div></div><div class="trial-note">현재는 결제 없는 기능 체험이에요. 결제 정보나 자동 구독을 등록하지 않아요.</div>${extra.trial?`${btn('아바타 모드로 돌아가기','avatar','','primary block')}<button class="text-button" data-action="end-trial">프리미엄 체험 종료</button>`:btn('결제 없이 프리미엄 체험하기','start-trial','','primary block')}</div>`);}
  function showCoach(){const p=person();if(!p){toast('먼저 추천 프로필을 다시 표시해 주세요.');return;}planner.personId=p.id;if(!canUseAvatar(extra)){premiumModal();return;}const c=coachPlan(user(),p,planner,tone,scenario);showModal(`<div class="modal-inner coach-modal">${modalHead('나의 아바타 코치',`${esc(p.name)} 님과의 만남을 함께 준비해요.`)}<div class="coach-heading"><span class="premium-label">Premium 체험</span><button class="text-button" data-action="premium">멤버십</button></div><div class="planner-selects"><div class="field"><label for="coach-person">만남 상대</label><select id="coach-person">${people().map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)} · ${x.age} · ${esc(x.mbti)}</option>`).join('')}</select></div><div class="field"><label for="coach-tone">나의 말투</label><select id="coach-tone"><option value="warm" ${tone==='warm'?'selected':''}>다정하고 자연스럽게</option><option value="calm" ${tone==='calm'?'selected':''}>차분하고 정중하게</option><option value="light" ${tone==='light'?'selected':''}>밝고 가볍게</option></select></div></div><div class="coach-route"><span class="source-tag">${esc(planner.city)} · 선택한 데이트 코스</span><h3>${esc(route().title)}</h3><p>${esc(c.routeReason)}</p><p>${esc(c.coordination)}</p><button class="text-button accent" data-action="edit-coach-route">지역·코스 바꾸기 ${icon('arrow')}</button></div><div class="coach-tip">${icon('heart')}<p>${esc(c.pace)}</p></div><div class="section-header coach-section"><h3>미리 연습하는 한마디</h3><span class="source-tag">취향 기반 기본 문구</span></div><p class="helper">${state().profile?'입력한 내 취향과 상대 프로필을 비교했어요.':'아직 내 성향을 입력하지 않아 예시 취향으로 준비했어요.'} 상대는 체험용 가상 인물이에요.</p><div class="conversation"><div class="bubble mine"><span>첫 인사</span><p>${esc(c.opener)}</p></div><div class="bubble mine"><span>데이트 제안</span><p id="coach-invitation">${esc(c.invitation)}</p><button class="bubble-copy" data-action="copy-coach" aria-label="데이트 제안 멘트 복사">${icon('copy')}</button></div></div><div class="scenario-tabs" role="group" aria-label="대화 연습 상황">${[['open','대화를 이어갈 때'],['short','답장이 짧을 때'],['busy','시간이 안 맞을 때']].map(([id,label])=>`<button class="filter-chip ${scenario===id?'active':''}" data-action="coach-scenario" data-value="${id}" aria-pressed="${scenario===id}">${label}</button>`).join('')}</div><div class="conversation"><div class="bubble theirs"><span>상대의 예상 멘트 · 가상 연습</span><p>${esc(c.scenario.reply)}</p></div><div class="bubble mine"><span>이렇게 이어가 볼까요</span><p>${esc(c.scenario.next)}</p></div></div><p class="helper scenario-note">실제 반응을 예측한 결과가 아닌 연습용 상황이에요. 상대의 대답과 의사를 먼저 들어주세요.</p><section class="coach-ai"><span class="premium-label">생성형 AI 브리핑</span><h3>이 취향과 코스로 새로 써볼까요?</h3><p>선택한 상대·지역·코스·말투를 함께 읽고 새로운 데이트 준비 노트를 만들어요.</p>${btn(`${icon('note')}AI 맞춤 브리핑 생성`,'ai-avatar','','primary block')}<small>기기 AI 지원 브라우저에서 사용 · 첫 실행 시 모델 다운로드</small></section></div>`);}
  function downloadFestival(f){const url=URL.createObjectURL(new Blob([festivalICS(f)],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`ieum-${f.id}.ics`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('달력 파일을 내려받아요. 달력 앱에서 가져오면 하루 전 알림이 추가돼요.');}
  function handleAction(action,target){const id=target.dataset.id,index=Number(target.dataset.index);
    switch(action){
      case 'choose-route':{const r=routesFor(planner.city,planner.date).find(x=>x.id===id);if(r){planner=normalizePlan({...planner,routeId:r.id,movie:r.mood==='영화'});persist();render();}break;}
      case 'date-for':{const p=PEOPLE.find(x=>x.id===id);if(p){planner.personId=id;switchCity(p.city);navigate('dates');}break;}
      case 'save-route':{const p=person();if(!p)break;planner.personId=p.id;if(extra.routes.some(r=>planKey(r)===planKey(planner))){toast('이미 저장한 코스예요.');break;}extra.routes.unshift({...planner});extra.routes=extra.routes.slice(0,20);const ok=persist();render();if(ok)toast('데이트 코스를 저장했어요. 아래에서 다시 불러올 수 있어요.');break;}
      case 'copy-route':copy(routeText(planner,person()));break;
      case 'load-route':if(extra.routes[index]){planner={...extra.routes[index]};if(state().hidden.includes(planner.personId)){toast('숨긴 상대의 코스예요. 내 프로필에서 숨김을 해제한 뒤 불러와 주세요.');break;}persist();render();document.getElementById('date-person')?.focus();window.scrollTo({top:0,behavior:'smooth'});}break;
      case 'remove-route':if(extra.routes[index]){extra.routes.splice(index,1);persist();render();toast('저장한 코스를 삭제했어요.');}break;
      case 'festivals':festivalCity='전체';onlySaved=false;festivalsModal();break;
      case 'save-festival':if(FESTIVALS.some(f=>f.id===id)){extra.festivals=extra.festivals.includes(id)?extra.festivals.filter(x=>x!==id):[...extra.festivals,id];persist();render();if(document.querySelector('.festival-modal'))festivalsModal();toast(extra.festivals.includes(id)?'축제를 알림함에 보관했어요. 하루 전 알림은 달력에 추가해 주세요.':'알림 보관을 취소했어요.');}break;
      case 'festival-calendar':{const f=FESTIVALS.find(x=>x.id===id);if(f)downloadFestival(f);break;}
      case 'festival-route':{const f=upcomingFestivals().find(x=>x.id===id);if(f){const date=festivalsOn(f.city,planner.date).some(x=>x.id===f.id)?planner.date:(koreaToday()>f.start?koreaToday():f.start);planner=normalizePlan({...planner,city:f.city,date,routeId:`festival-${f.id}`,movie:false});persist();navigate('dates');toast(`${date} · ${f.name} 코스를 골랐어요.`);}break;}
      case 'remove-photo':extra.photo='';persist();render();toast('프로필 사진을 삭제했어요.');break;
      case 'premium':premiumModal();break;
      case 'start-trial':extra.trial=true;persist();render();showCoach();break;
      case 'end-trial':extra.trial=false;persist();render();premiumModal();toast('프리미엄 체험을 종료했어요.');break;
      case 'avatar':showCoach();break;
      case 'edit-coach-route':navigate('dates');break;
      case 'coach-scenario':scenario=target.dataset.value;showCoach();break;
      case 'copy-coach':copy(document.getElementById('coach-invitation').textContent);break;
      case 'ai-avatar':if(canUseAvatar(extra)){const p=person();showAI('avatar',p.id,{date:planner.date,route:route(),steps:itinerary(planner),tone,scenario,mbti:extra.mbti});}else premiumModal();break;
      default:return false;
    }return true;
  }
  async function handleChange(target){
    switch(target.id){
      case 'date-city':switchCity(target.value);render();break;
      case 'date-person':planner.personId=target.value;persist();render();break;
      case 'plan-movie':planner.movie=target.checked;planner=normalizePlan(planner);persist();render();break;
      case 'plan-stay':planner.stay=target.checked;persist();render();break;
      case 'plan-start':if(!target.value){target.value=planner.start;toast('만나는 시간을 입력해 주세요.');break;}planner=normalizePlan({...planner,start:target.value});persist();render();break;
      case 'plan-date':{const wasFestival=Boolean(route().festivalId);planner=normalizePlan({...planner,date:target.value});persist();render();if(wasFestival&&!route().festivalId)toast('축제 기간과 달라 일반 코스로 바꿨어요.');break;}
      case 'my-mbti':extra.mbti=normalizeMBTI(target.value);{const ok=persist();render();if(ok)toast(extra.mbti?`${extra.mbti}로 저장했어요.`:'MBTI를 미설정으로 바꿨어요.');}break;
      case 'profile-photo':{const file=target.files?.[0];if(!file||photoBusy)break;photoBusy=true;target.disabled=true;const status=document.getElementById('photo-status');status.textContent='사진을 준비하고 있어요…';try{const photo=await preparePhoto(file);const previous=extra.photo;extra.photo=photo;if(!persist()){extra.photo=previous;throw new Error('사진을 저장하지 못했어요. 저장 공간을 확인해 주세요.');}render();toast('프로필 사진을 저장했어요.');}catch(error){if(status.isConnected)status.textContent=error.message;toast(error.message);}finally{photoBusy=false;if(target.isConnected){target.disabled=false;target.value='';}}break;}
      case 'coach-person':planner.personId=target.value;persist();showCoach();break;
      case 'coach-tone':tone=target.value;showCoach();break;
      case 'festival-city':festivalCity=target.value;festivalsModal();break;
      case 'date-festival-city':dateFestivalCity=target.value;render();break;
      case 'festival-saved-only':onlySaved=target.checked;festivalsModal();break;
    }
  }
  function planMeeting(request){
    if(state().hidden.includes(request.personId)){toast('숨긴 상대의 만남이에요. 내 프로필에서 숨김을 해제해 주세요.');return;}
    planner=normalizePlan({...planner,personId:request.personId,city:request.city,date:request.date,start:request.time||planner.start,routeId:request.city===planner.city?planner.routeId:''});persist();navigate('dates');
  }
  function header(){const p=document.querySelector('.header-profile');if(p)p.innerHTML=avatar('header-avatar');const bell=document.getElementById('festival-bell');if(bell){const due=upcomingFestivals().filter(f=>extra.festivals.includes(f.id)).length;bell.innerHTML=icon('bell')+(due?`<span class="notification-dot">${due}</span>`:'');bell.setAttribute('aria-label',`축제 알림${due?` ${due}개 보관 중`:''}`);}}
  function reset(){extra={photo:'',mbti:'',trial:false,planner:normalizePlan(),routes:[],festivals:[]};planner={...extra.planner};try{storage.setItem(LEGACY_EXTRA_KEY,'{}');storage.setItem(EXTRA_KEY,JSON.stringify(extra));}catch{toast('이 브라우저의 저장 정보를 지우지 못했어요.');}}
  return {dates,planMeeting,profileCard,membership,compactPremium,compactFestival,avatar,header,handleAction,handleChange,reset,get extra(){return extra;}};
}
