const EXTRA_KEY='ieum:extra:v1';
const PROFILE_KEY='meetrust:v2';
const MBTIS=['ENFP','ENFJ','ENTP','ENTJ','ESFP','ESFJ','ESTP','ESTJ','INFP','INFJ','INTP','INTJ','ISFP','ISFJ','ISTP','ISTJ'];
const FESTIVALS=[
  {city:'전주',name:'전주 한옥마을 가을 데이트',date:'가을 추천',tag:'한옥·야경'},
  {city:'군산',name:'시간여행마을 & 야간 산책',date:'주말 추천',tag:'근대문화·사진'},
  {city:'남원',name:'광한루원 야간 산책',date:'저녁 추천',tag:'산책·야경'},
  {city:'임실',name:'치즈테마파크 시즌 코스',date:'주말 추천',tag:'체험·먹거리'}
];
const ROUTES={
  전주:{title:'전주 감성 반나절',meet:'객사·한옥마을',movie:'CGV 전주고사',meal:'한옥마을/객리단길 식사',cafe:'객리단길 감성 카페',spot:'전주한옥마을 · 전주천 산책',stay:'한옥스테이 또는 시내 숙박',times:['17:30','18:00','20:00','21:10','22:00']},
  군산:{title:'군산 바다+레트로 데이트',meet:'월명동',movie:'군산 시내 영화관',meal:'근대문화거리 근처 식사',cafe:'월명동 로스터리 카페',spot:'은파호수공원 또는 선유도',stay:'군산 시내/선유도 숙박',times:['16:30','17:00','19:00','20:10','21:30']},
  익산:{title:'익산 편한 저녁 데이트',meet:'영등동',movie:'익산 시내 영화관',meal:'영등동 저녁식사',cafe:'영등동 카페',spot:'중앙체육공원 산책',stay:'익산역 인근 숙박',times:['18:00','18:20','20:20','21:20','22:10']},
  임실:{title:'임실 체험형 데이트',meet:'임실치즈테마파크',movie:'체험 코스로 대체',meal:'치즈 요리·지역 식사',cafe:'테마파크/임실 카페',spot:'임실치즈테마파크 산책',stay:'임실·전주 이동 후 숙박',times:['14:00','14:20','16:30','17:30','19:00']},
  남원:{title:'남원 야경 데이트',meet:'광한루원',movie:'남원 시내 문화공간',meal:'광한루원 인근 식사',cafe:'요천 근처 카페',spot:'광한루원 · 요천 야간산책',stay:'남원 시내 한옥/호텔',times:['17:00','17:20','19:00','20:10','21:20']},
  완주:{title:'완주 느긋한 주말 데이트',meet:'삼례',movie:'문화예술촌 관람',meal:'삼례 지역 식사',cafe:'대형 베이커리 카페',spot:'삼례문화예술촌 산책',stay:'완주 또는 전주 숙박',times:['15:00','15:20','17:20','18:30','20:00']}
};
function extras(){try{return JSON.parse(localStorage.getItem(EXTRA_KEY)||'{}')}catch{return {}}}
function saveExtras(v){localStorage.setItem(EXTRA_KEY,JSON.stringify(v))}
function appState(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){let t=document.querySelector('.ieum-toast2');if(!t){t=document.createElement('div');t.className='ieum-toast2';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function ensureModal(){let m=document.getElementById('ieum-upgrade-modal');if(!m){m=document.createElement('div');m.id='ieum-upgrade-modal';m.className='ieum-modal';m.innerHTML='<div class="ieum-modal-card"><div class="ieum-modal-head"><strong id="ieum-modal-title">전북 잇음</strong><button class="ieum-close" data-up="close">×</button></div><div class="ieum-modal-body" id="ieum-modal-body"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('[data-up="close"]'))m.classList.remove('show')})}return m}
function openModal(title,body){const m=ensureModal();document.getElementById('ieum-modal-title').textContent=title;document.getElementById('ieum-modal-body').innerHTML=body;m.classList.add('show')}
function avatarMode(){const state=appState(),name=state.profile?.name||'당신';openModal('AI AVATAR MODE',`<div class="avatar-shell"><div class="avatar-title"><div><span class="premium-chip">PREMIUM</span><h2>AI가 내 연애 코파일럿이 된다.</h2><p>${esc(name)}님의 성향과 상대의 취향·생활권·대화 스타일을 바탕으로, 첫 멘트부터 예상 반응과 데이트 루트까지 한 화면에 정리해요.</p></div></div><div class="avatar-target"><div class="avatar-face">서</div><div><small>오늘의 잇음 · 상대 프로필 분석</small><b>서연 · 23 · 익산 거주 / 전주 통학</b></div></div><div class="avatar-grid"><div class="avatar-box"><small>추천 첫 멘트</small><h3>부담 없이 시작하기</h3><div class="avatar-chat"><span>AI 추천</span><b>“전주에서 요즘 자주 가는 카페 있어요? 저도 조용한 곳 좋아해서 궁금했어요 :)”</b></div></div><div class="avatar-box"><small>예상 반응</small><h3>상대가 이렇게 답할 가능성이 높아요</h3><p>“저는 객사 쪽 자주 가요 ㅎㅎ 카페는 조용한 데 좋아해요.”</p><div class="avatar-chat"><span>그 다음 추천 답변</span><b>“그럼 객사 쪽에서 커피 한잔해도 좋겠네요. 평일 저녁 괜찮아요?”</b></div></div><div class="avatar-box"><small>대화 가이드</small><h3>오늘은 이런 주제가 좋아요</h3><p>카페 · 여행 · 음악. 질문은 짧게, 답변은 상대보다 조금 짧게. 첫 대화에서 미래 연애관을 깊게 캐묻는 건 피하는 편이 좋아요.</p></div><div class="avatar-box premium"><small>AI DATE COACH</small><h3>상대 맞춤 데이트</h3><p>조용한 곳 선호 + 전주 평일 생활권 → 객리단길 식사 → 한옥마을 야간 산책 → 카페 코스를 추천합니다.</p><div class="premium-lock"><span><strong>Premium</strong><br>예상 멘트·데이트 코치 전체 해금</span><button data-up="premium">체험하기</button></div></div></div></div>`)}
function routeMarkup(city,stay=false){const r=ROUTES[city]||ROUTES.전주;return `<div class="route-panel"><section class="route-summary"><small>AI DATE ROUTE · ${esc(city)}</small><h2>${esc(r.title)}</h2><p>상대의 취향과 이동 부담을 고려한 데모 코스예요. 실제 서비스에선 영업시간·거리·축제를 실시간 반영합니다.</p><div class="route-option"><span>만남 지역</span><b>${esc(r.meet)}</b></div><div class="route-option"><span>코스 길이</span><b>약 4~5시간</b></div><div class="route-option"><span>분위기</span><b>부담 적은 첫 데이트</b></div><div class="stay-toggle"><span>😏 숙박 코스도 볼까요?<br><small>완전 선택사항입니다.</small></span><button data-up="toggle-stay" data-city="${esc(city)}">${stay?'숨기기':'보기'}</button></div>${stay?`<div class="route-option"><span>선택 코스</span><b>${esc(r.stay)}</b></div>`:''}<div class="route-actions"><button class="sub" data-up="nearby">이 지역 카페 찾기</button><button class="main" data-up="save-route">이 코스 저장</button></div></section><section class="route-timeline"><div class="timeline-item"><time>${r.times[0]}</time><div><b>만남 · ${esc(r.meet)}</b><p>서로 이동하기 편한 공개된 장소에서 시작</p></div></div><div class="timeline-item"><time>${r.times[1]}</time><div><b>영화/놀거리 · ${esc(r.movie)}</b><p>어색한 첫 1시간을 자연스럽게 넘기는 코스</p></div></div><div class="timeline-item"><time>${r.times[2]}</time><div><b>밥 · ${esc(r.meal)}</b><p>대화하기 좋은 식사 시간</p></div></div><div class="timeline-item"><time>${r.times[3]}</time><div><b>카페 · ${esc(r.cafe)}</b><p>대화가 잘 맞으면 조금 더 머무르기</p></div></div><div class="timeline-item"><time>${r.times[4]}</time><div><b>지역 명소 · ${esc(r.spot)}</b><p>사진·산책으로 자연스럽게 마무리</p></div></div>${stay?`<div class="timeline-item"><time>선택</time><div><b>숙박 · ${esc(r.stay)}</b><p>두 사람 모두 원할 때만 선택하는 추가 코스</p></div></div>`:''}</section></div>`}
function datePlanner(city='전주',stay=false){openModal('전북 AI 데이트 플래너',`<div class="city-tabs">${Object.keys(ROUTES).map(c=>`<button data-up="city" data-city="${c}" class="${c===city?'active':''}">${c}</button>`).join('')}</div><div id="ieum-route">${routeMarkup(city,stay)}</div>`)}
function discoverUpgrade(){const page=document.querySelector('#content');if(!page||document.querySelector('.ieum-upgrade-wrap'))return;const intro=page.querySelector('.page-intro');if(!intro)return;const wrap=document.createElement('section');wrap.className='ieum-upgrade-wrap';wrap.innerHTML=`<div class="ieum-hero-card"><div class="ieum-hero-top"><div><span class="eyebrow-new">✦ AI AVATAR MODE</span><h2>쑥맥이어도 괜찮아요.<br>AI가 연애 코파일럿이 되어줄게요.</h2><p>상대 프로필을 읽고 추천 멘트, 예상 반응, 피해야 할 화제, 실제 데이트 루트까지 준비합니다.</p></div><span class="premium-chip">PREMIUM</span></div><div class="ieum-hero-actions"><button class="ieum-up-btn primary" data-up="avatar">아바타 모드 체험</button><button class="ieum-up-btn ghost" data-up="planner">데이트 루트 만들기</button></div></div><div class="ieum-feature-grid"><article class="ieum-mini-card"><div class="mini-icon">🧠</div><h3>MBTI + 행동 성향</h3><p>MBTI는 참고 신호로만 쓰고 실제 응답·취향·생활권과 함께 봐요.</p></article><article class="ieum-mini-card"><div class="mini-icon">📍</div><h3>지역별 데이트 루트</h3><p>전주·군산·익산·임실·남원·완주에서 실제 코스를 고를 수 있어요.</p></article><article class="ieum-mini-card"><div class="mini-icon">✨</div><h3>오늘의 잇음</h3><p>그냥 추천이 아니라 오늘 실제로 이어질 가능성이 높은 만남을 보여줘요.</p></article></div><div class="ieum-festival"><div class="ieum-festival-head"><h3>다가오는 전북 데이트 아이디어</h3><span>프로토타입 추천</span></div><div class="festival-scroll">${FESTIVALS.map(f=>`<div class="festival-pill"><b>${f.city} · ${f.name}</b><small>${f.date}<br>${f.tag}</small><em>데이트 코스에 추가</em></div>`).join('')}</div></div>`;intro.insertAdjacentElement('afterend',wrap);replaceTodayText()}
function replaceTodayText(){document.querySelectorAll('#content h1,#content h2,#content strong,#content span').forEach(el=>{if(el.childElementCount)return;const txt=el.textContent;if(txt==='오늘의 추천'||txt==='오늘의 발견'||txt==='오늘의 3명 보기')el.textContent=txt.replace('오늘의 추천','오늘의 잇음').replace('오늘의 발견','오늘의 잇음').replace('오늘의 3명 보기','오늘의 잇음 보기')})}
function profileUpgrade(){if(location.hash!=='#profile')return;const page=document.querySelector('#content');if(!page||document.querySelector('.profile-upgrade'))return;const anchor=page.querySelector('.wide-panel')||page.querySelector('.page-intro');if(!anchor)return;const x=extras(),state=appState();const box=document.createElement('section');box.className='profile-upgrade';const initials=state.profile?.name?.slice(0,1)||'나';box.innerHTML=`<div class="profile-photo">${x.photo?`<img src="${x.photo}" alt="내 프로필 사진">`:esc(initials)}</div><div class="profile-upgrade-copy"><h3>내 프로필을 조금 더 나답게</h3><p>사진과 MBTI를 추가하면 AI 아바타 모드와 오늘의 잇음 설명에 함께 반영돼요.</p><div class="profile-upgrade-actions"><label>사진 추가<input id="ieum-photo" type="file" accept="image/*"></label><select id="ieum-mbti" aria-label="MBTI"><option value="">MBTI 선택</option>${MBTIS.map(m=>`<option ${x.mbti===m?'selected':''}>${m}</option>`).join('')}</select><button class="ieum-up-btn" style="padding:9px 11px;background:#17171a;color:#fff" data-up="avatar">AI 아바타 보기</button></div></div>`;anchor.parentElement.insertBefore(box,anchor);box.querySelector('#ieum-mbti').addEventListener('change',e=>{const d=extras();d.mbti=e.target.value;saveExtras(d);toast('MBTI가 저장됐어요')});box.querySelector('#ieum-photo').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1500000){toast('사진은 1.5MB 이하로 선택해주세요');return}const reader=new FileReader();reader.onload=()=>{const d=extras();d.photo=reader.result;saveExtras(d);box.querySelector('.profile-photo').innerHTML=`<img src="${reader.result}" alt="내 프로필 사진">`;toast('프로필 사진이 저장됐어요')};reader.readAsDataURL(file)})}
function dateUpgrade(){if(location.hash!=='#dates')return;const page=document.querySelector('#content');if(!page||document.querySelector('.ieum-date-insert'))return;const intro=page.querySelector('.page-intro');if(!intro)return;const div=document.createElement('div');div.className='ieum-date-insert ieum-hero-card';div.style.margin='0 0 20px';div.innerHTML=`<div class="ieum-hero-top"><div><span class="eyebrow-new">AI DATE PLANNER</span><h2>지역부터 고르면,<br>데이트 하루를 통째로 짜드려요.</h2><p>만남 → 영화/놀거리 → 밥 → 카페 → 지역 명소 → 숙박(선택)까지. 상대 취향과 전북 생활권을 함께 봅니다.</p></div></div><div class="ieum-hero-actions"><button class="ieum-up-btn primary" data-up="planner">지역별 루트 만들기</button><button class="ieum-up-btn ghost" data-up="avatar">아바타 모드로 상대 분석</button></div>`;intro.insertAdjacentElement('afterend',div)}
function enhance(){discoverUpgrade();profileUpgrade();dateUpgrade();replaceTodayText()}
const observer=new MutationObserver(()=>{clearTimeout(observer._t);observer._t=setTimeout(enhance,40)});observer.observe(document.getElementById('content'),{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(enhance,60));document.addEventListener('click',e=>{const t=e.target.closest('[data-up]');if(!t)return;const a=t.dataset.up;if(a==='avatar'){avatarMode()}else if(a==='planner'){datePlanner()}else if(a==='premium'){toast('Premium 데모가 활성화됐어요 ✨')}else if(a==='city'){document.querySelectorAll('.city-tabs button').forEach(b=>b.classList.toggle('active',b===t));document.getElementById('ieum-route').innerHTML=routeMarkup(t.dataset.city,false)}else if(a==='toggle-stay'){document.getElementById('ieum-route').innerHTML=routeMarkup(t.dataset.city,t.textContent.trim()==='보기')}else if(a==='nearby'){toast('기존 “이 지역 카페 찾기” 기능과 연결되는 자리예요')}else if(a==='save-route'){toast('데이트 코스를 저장했어요')}});setTimeout(enhance,120);